const PORT = process.env.PORT;
const MONGO_URI = process.env.MONGO_URI;
const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const ADMIN_JWT_SECRET = process.env.ADMIN_JWT_SECRET;
const ADMIN_NAME = process.env.ADMIN_NAME;
const OTP_API_KEY = process.env.OTP_API_KEY;
const OTP_CAMPAIGN = process.env.OTP_CAMPAIGN;
const OTP_PE_ID = process.env.OTP_PE_ID;
const OTP_ROUTE = process.env.OTP_ROUTE;
const OTP_SENDER_ID = process.env.OTP_SENDER_ID;
const OTP_TEMPLATE_ID = process.env.OTP_TEMPLATE_ID;
const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || "7d";
const ANDROID_APP_SIGNATURE = process.env.ANDROID_APP_SIGNATURE;

module.exports = {
  PORT,
  MONGO_URI,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  ADMIN_JWT_SECRET,
  ADMIN_NAME,
  OTP_API_KEY,
  OTP_CAMPAIGN,
  OTP_PE_ID,
  OTP_ROUTE,
  OTP_SENDER_ID,
  OTP_TEMPLATE_ID,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  ANDROID_APP_SIGNATURE,
};
